name: car_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: null
  dartz: null
  dio: null
  equatable: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_localizations:
    sdk: flutter
  intl: 
  go_router: 
  flutter_svg: 
  flutter_staggered_grid_view:
  flutter_map:
  http: 
  flutter_map_location_marker:
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: null
  latlong2: ^0.9.1
  location: ^6.0.2
  flutter_rating_bar:

  shared_preferences: null

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/vectors/
    - assets/images/

  fonts:
    - family: JannaLT
      fonts:
        - asset: assets/fonts/JannaLT-Bold.ttf
